CREATE SCHEMA `carites`;

#Criação das tabelas sem FK
CREATE TABLE carites.usuario_pj (
ID_PJ INT,
CNPJ VARCHAR(50) NOT NULL,
NOME_FANTASIA VARCHAR(255) NOT NULL,
RAZAO_SOCIAL VARCHAR(255) NOT NULL,
SITE VARCHAR(500),
TELEFONE VARCHAR(15), 
EMAIL VARCHAR(255),
SENHA VARCHAR(20) NOT NULL,
INSCRICAO VARCHAR(50),
ESTADO VARCHAR(50),
UNIQUE(CNPJ),
PRIMARY KEY(ID_PJ)
);

CREATE TABLE carites.usuario_pf (
ID_PF INT,
CPF VARCHAR(11) NOT NULL,
NOME_COMPLETO TEXT NOT NULL,
DATA_NASCIMENTO DATE,
TELEFONE INT, 
EMAIL VARCHAR(255),
SENHA VARCHAR(20) NOT NULL,
UNIQUE(CPF),
PRIMARY KEY(ID_PF)
);

CREATE TABLE carites.categoria (
ID_CATEGORIA INT, 
NOME TEXT,
PRIMARY KEY(ID_CATEGORIA)
);

CREATE TABLE carites.doacao_valor (
ID_DOACAO_VALOR INT, 
VALOR FLOAT NOT NULL,
PRIMARY KEY(ID_DOACAO_VALOR)
);

CREATE TABLE carites.instituicao_caridade (
ID_INSTCARIDADE INT, 
CNPJ VARCHAR(255) NOT NULL, 
DESCRICAO LONGTEXT NOT NULL, 
NOME_FANTASIA VARCHAR(500) NOT NULL, 
TELEFONE VARCHAR(15), 
CEP VARCHAR(10), 
NUMERO INT, 
COMPLEMENTO VARCHAR(500), 
UNIQUE(CNPJ),
PRIMARY KEY(ID_INSTCARIDADE)
);

CREATE TABLE carites.orcamento(
ID_ORCAMENTO INT,
TOTAL FLOAT,
CUSTO FLOAT,
LUCRO FLOAT,
PERIODO_INICIAL DATE,
PERIODO_FINAL DATE,
PRIMARY KEY(ID_ORCAMENTO)
);

#Criação das tabelas com FK 

CREATE TABLE carites.pedido (
ID_PEDIDO INT, 
TIPO_PAGAMENTO TEXT,
DESCONTO DOUBLE, 
FRETE DOUBLE, 
CEP VARCHAR(10), 
NUMERO INT, 
COMPLEMENTO VARCHAR(500), 
ID_PJ INT,
ID_PF INT,
PRIMARY KEY(ID_PEDIDO),
FOREIGN KEY(ID_PJ) REFERENCES carites.usuario_pj(ID_PJ),
FOREIGN KEY(ID_PF) REFERENCES carites.usuario_pf(ID_PF)
);

CREATE TABLE carites.nota_fiscal_venda (
ID_NF INT,
DATA DATE, 
TOTAL FLOAT,
ID_PEDIDO INT,
PRIMARY KEY(ID_NF),
FOREIGN KEY(ID_PEDIDO) REFERENCES carites.pedido(ID_PEDIDO)
); 

CREATE TABLE carites.doacao_produto (
ID_DOACAO_PRODUTO INT,
TIPO_ENTREGA ENUM('Envio', 'Retirada'),
DESCRICAO_MARCA TEXT NOT NULL,
CEP VARCHAR(10), 
NUMERO INT, 
COMPLEMENTO VARCHAR(500), 
ID_PJ INT,
ID_PF INT,
PRIMARY KEY(ID_DOACAO_PRODUTO),
FOREIGN KEY(ID_PJ) REFERENCES carites.usuario_pj(ID_PJ),
FOREIGN KEY(ID_PF) REFERENCES carites.usuario_pf(ID_PF)
);

CREATE TABLE carites.nota_fiscal_doacao (
ID_NF_DOACAO INT, 
DATA DATETIME, 
ID_DOACAO_PRODUTO  INT, 
PRIMARY KEY(ID_NF_DOACAO),
FOREIGN KEY(ID_DOACAO_PRODUTO) REFERENCES carites.doacao_produto(ID_DOACAO_PRODUTO)
);

CREATE TABLE carites.item_doacao (
ID_ITEM_DOACAO INT, 
NOME TEXT, 
CATEGORIA TEXT,
DESCRICAO_PRODUTO LONGTEXT,
IMAGEM_PRODUTO BLOB,
QUANTIDADE INT,
ID_DOACAO_PRODUTO INT,
PRIMARY KEY(ID_ITEM_DOACAO),
FOREIGN KEY(ID_DOACAO_PRODUTO) REFERENCES carites.doacao_produto(ID_DOACAO_PRODUTO)
);

CREATE TABLE carites.produto (
ID_PRODUTO INT, 
ID_CATEGORIA INT, 
ID_ITEM_DOACAO INT,
PRIMARY KEY(ID_PRODUTO),
FOREIGN KEY(ID_ITEM_DOACAO) REFERENCES carites.item_doacao(ID_ITEM_DOACAO),
FOREIGN KEY(ID_CATEGORIA) REFERENCES carites.categoria(ID_CATEGORIA)
);

CREATE TABLE carites.item_pedido(
ID_ITEM_PEDIDO INT, 
QUANTIDADE INT, 
SUBTOTAL FLOAT,
ID_PEDIDO INT, 
ID_PRODUTO INT,
PRIMARY KEY(ID_ITEM_PEDIDO),
FOREIGN KEY(ID_PEDIDO) REFERENCES carites.pedido(ID_PEDIDO),
FOREIGN KEY(ID_PRODUTO) REFERENCES carites.produto(ID_PRODUTO)
);

CREATE TABLE carites.nota_fiscal_doacao_valor (
ID_NF_DOACAO_VALOR INT, 
DATA DATETIME,
ID_DOACAO_VALOR INT,
ID_INSTCARIDADE INT,
PRIMARY KEY(ID_NF_DOACAO_VALOR),
FOREIGN KEY(ID_INSTCARIDADE) REFERENCES carites.instituicao_caridade(ID_INSTCARIDADE),
FOREIGN KEY(ID_DOACAO_VALOR) REFERENCES carites.doacao_valor(ID_DOACAO_VALOR)
);

#Drop tables das tabelas sem FK
DROP TABLE carites.instituicao_caridade;
DROP TABLE carites.doacao_valor;
DROP TABLE carites.categoria;
DROP TABLE carites.usuario_pf;
DROP TABLE carites.usuario_pj;


